//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPplutenkoKaskad
{
    using System;
    using System.Collections.Generic;
    
    public partial class Заказанные_товары
    {
        public int ID_товара { get; set; }
        public int ID_заказа { get; set; }
        public string Количество_товаров_в_заказе { get; set; }
        public string Стоимость_товаров_в_заказе { get; set; }
    
        public virtual Заказы Заказы { get; set; }
        public virtual Товары Товары { get; set; }
    }
}
