//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPplutenkoKaskad
{
    using System;
    using System.Collections.Generic;
    
    public partial class Товары
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Товары()
        {
            this.Заказанные_товары = new HashSet<Заказанные_товары>();
        }
    
        public int ID_товара { get; set; }
        public string Наименование_товара { get; set; }
        public string Количество_на_складе { get; set; }
        public string Цена_за_единицу_товара { get; set; }
        public Nullable<int> ID_поставщика { get; set; }
    
        public virtual Поставщики Поставщики { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Заказанные_товары> Заказанные_товары { get; set; }
    }
}
